services:
  mongodb:
    image: mongo:latest
    container_name: aladia-mongodb
    restart: unless-stopped
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: aladia-challenge
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
